
stages:
  - publish

# trigger releasing to GitHub.com
publish-to-github:
  stage: publish
  variables: 
    GIT_DEPTH: 0
  image: 
    name: artifactory.sofa.dev/monitoring-docker-local/goreleaser:1.0.0
    entrypoint: ['']
  script:
    - git config --global user.name "$GITHUB_USER"
    - git config --global user.email "$GITHUB_EMAIL"
    - git config --global credential.helper store
    - echo "https://$GITHUB_USER:$GITHUB_PASS@github.com" > ~/.git-credentials
    - git remote add github $GITHUB_REPO_URL
    - git ls-files
    - git checkout main
    - git push -u github main
    - git push github $CI_COMMIT_TAG
  tags:
    - dockermachine
  allow_failure: false
  rules:
    - if: $CI_COMMIT_TAG